@MusicMan.Web_HostAddress = http://localhost:5031

GET {{MusicMan.Web_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{MusicMan.Web_HostAddress}}/api/collection/barcodes
Content-Type: application/json

{
	"barcode": "0603497831297"
}

###
